config/routes.rb
Rails.application.routes.draw do

  root "welcome#welcome"

  resources :reservations
  resources :items
  resources :users

  get 'login', to: "sessions#new", as: "login"
  post 'login', to: "sessions#create"
  post "logout", to: "sessions#destroy", as: "logout"
  get 'signup', to: "users#new", as: "signup"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :seller, :class_name => "User"
  has_many :reservations


end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :item
  belongs_to :renter, :class_name => "User"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum status: {active: 1, inactive: 0}

  has_many :items
  has_many :reservations, :foreign_key => "renter_id"

  validates :password_digest, :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :seller_id)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :logged_in?

  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  def logged_in?
    !!current_user
  end

  def current_user
    if (session[:user_id])
       @user = User.find(:user_id)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       session[:user_id] = @user.id
       redirect_to root_path
    else
       redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
    @items = Item.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/new.html.erb
<h1>POST ITEMS</h1>
<%= form_for @item do |f| %>
  <%= f.label :name, :class => "item-name"%>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.hidden_field :seller_id, value: session[:user_id] %>
  <%= f.submit "Post Item" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EscapePractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/welcome/_item.html.erb
<%= item.name %>
<%= item.description %>

app/views/welcome/welcome.html.erb
<h1>Welcome To Escape!</h1>
<% if session[:user_id] %>
  <%= link_to "Logout", logout_path, method: 'post' %>
  <%= link_to "Post Item", new_item_path, :class => "post_item_link"%>
<% else %>
  <%= link_to "Sign Up", signup_path%>
  <%= link_to "Login", login_path%>
<% end %>

<%= render :partial => "item", :collection => @items %>